import shoes1 from "../images/1.jpg";
import shoes2 from "../images/2.jpg";
import shoes3 from "../images/3.jpg";
import shoes4 from "../images/4.jpg";
import shoes5 from "../images/5.jpg";
import shoes6 from "../images/6.jpg";
import shoes7 from "../images/7.jpg";
import shoes8 from "../images/8.jpg";
import shoes9 from "../images/9.jpg";

const store = [
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "1",
    img: shoes1,
    alt: "shoes1",
    price: "25$ USD",
    color: ["white", "black", "red", "yellow"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10", "10.5", "11"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "2",
    img: shoes2,
    alt: "shoes2",
    price: "55$ USD",
    color: ["black", "red", "blue"],
    size: ["6", "6.5", "7", "7.5", "8"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "3",
    img: shoes3,
    alt: "shoes3",
    price: "44,9$ USD",
    color: ["grey", "brown", "red", "pink"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "4",
    img: shoes4,
    alt: "shoes4",
    price: "15,5$ USD",
    color: ["red", "blue", "pink", "grey"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10", "10.5", "11"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "5",
    img: shoes5,
    alt: "shoes5",
    price: "95$ USD",
    color: ["white", "black", "red", "yellow"],
    size: ["6", "6.5", "7"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "6",
    img: shoes6,
    alt: "shoes6",
    price: "75$ USD",
    color: ["white", "black", "red", "yellow"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10", "10.5", "11"],
    quantity: ["1", "2", "3", "4", "5"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "7",
    img: shoes7,
    alt: "shoes7",
    price: "22,9$ USD",
    color: ["white", "black", "red", "yellow"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10", "10.5", "11"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "8",
    img: shoes8,
    alt: "shoes8",
    price: "44,4$ USD",
    color: ["white", "black", "red", "yellow"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10", "10.5", "11"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
  {
    name: "New Balance",
    desc: "Suede fabric pointed toe stylish cut front low heel sharp on-trend toe point raised heel drop sides unique silhouette. Bow detail metallic eyelets leather lining luxurious finish classic courts formal slingback square toe contrasting cap.",
    model: "9",
    img: shoes9,
    alt: "shoes9",
    price: "74,4$ USD",
    color: ["white", "black", "red", "yellow"],
    size: ["6", "6.5", "7", "7.5", "8", "8,5", "9", "9.5", "10", "10.5", "11"],
    quantity: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    shipping: "Free shipping",
  },
];

export default store;
